# Generated by Django 4.2.2 on 2023-06-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
