# Generated by Django 4.1.7 on 2023-06-29 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.categories'),
        ),
    ]
